### ISSUE TITLE
Feature request: output list of sent messages

### ISSUE THREAD

**Issue by bkeepers** [kytrinyx/mailmerge#2]
I just used this to send a batch of messages and got a failure. I have no clue how many of the emails were actually sent. It'd be great if this output the status as messages were sent so you could identify failures.

```
$ CSV=oss-alley.csv TEMPLATE=oss-alley.txt ./mailmerge       
/Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/protocol.rb:176:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/protocol.rb:154:in `readuntil'
	from /Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/protocol.rb:164:in `readline'
	from /Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/smtp.rb:950:in `recv_response'
	from /Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/smtp.rb:553:in `block in do_start'
	from /Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/smtp.rb:960:in `critical'
	from /Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/smtp.rb:553:in `do_start'
	from /Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/smtp.rb:518:in `start'
	from /Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
	from /Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/mail-2.6.4/lib/mail/message.rb:253:in `deliver!'
	from /Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pony-1.11/lib/pony.rb:176:in `deliver'
	from /Users/bkeepers/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pony-1.11/lib/pony.rb:166:in `mail'
	from /Users/bkeepers/projects/mailmerge/lib/email.rb:8:in `dispatch'
	from ./mailmerge:19:in `block in <main>'
```

**Comment by kytrinyx** [comment]
added in https://github.com/kytrinyx/mailmerge/commit/b64a3236157b6cd825bada3311c56e69a3ec99be
